name: Weekly ETL Update

on:
  schedule:
    - cron: '0 3 * * 1'  # Executa toda segunda-feira às 3 AM UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  update-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Crawler
        run: |
          cd src/coleta
          scrapy crawl mercadolivre -o ../../data/data.jsonl

      - name: Transform Data
        run: |
          cd src/transform
          python run_transformation.py

      - name: Commit and Push Database
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'vorges-data'
          git config --global user.email 'vinicius.jborges36@gmail.com'
          git add data/price_notebooks_ml.db
          git commit -m "Update database with new data from workflow run"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:master
