name: Weekly ETL Update

on:
  schedule:
    - cron: '0 3 * * 1'  # Executa toda segunda-feira às 3 AM UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  update-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Crawler
        run: |
          cd src/coleta
          scrapy crawl mercadolivre -o ../../data/data.jsonl

      - name: Transform Data
        run: |
          cd ../..
          python src/transform/run_transformation.py

      - name: Run Streamlit App
        run: |
          nohup streamlit run Home.py &  # Executa o Streamlit em segundo plano
